### ISSUE TITLE
start () throws ContentTypeError

### ISSUE THREAD

**Issue by ed2050** [fronzbot/blinkpy#959]
**Describe the bug**
blink.start () throws an error on even the simplest example from the docs.  Every call to start, with or without an auth object, throws the same exception.  

Sometimes it prompts for username and password first (if not already provided).  A 2FA code is sent to my contact info.  But I never get a chance to enter it as the exception crashes out the program.

**To Reproduce**
I run the most basic example from docs:
```py
async def start():
    blink = Blink(session=ClientSession())
    await blink.start()
    return blink

blink = asyncio.run(start())
```

Results are:
```
Username:[redacted]
Password:[redacted]
# pauses a few seconds after I hit enter, then:
Traceback (most recent call last):
  File "/Users/dev/bin/blinkit.py", line 140, in <module>
    main (sys.argv [ 1: ])
  File "/Users/dev/bin/blinkit.py", line 118, in main
    blink = asyncio.run (open_session ())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/dev/bin/blinkit.py", line 49, in open_session
    await blink.start ()
  File "/Users/dev/Library/Python/3.8/lib/python/site-packages/blinkpy/blinkpy.py", line 115, in start  
    await self.get_homescreen()
  File "/Users/dev/Library/Python/3.8/lib/python/site-packages/blinkpy/blinkpy.py", line 176, in get_homescreen
    self.homescreen = await api.request_homescreen(self)
  File "/Users/dev/Library/Python/3.8/lib/python/site-packages/blinkpy/helpers/util.py", line 177, in wrapper
    return await method(*args, **kwargs)
  File "/Users/dev/Library/Python/3.8/lib/python/site-packages/blinkpy/api.py", line 183, in request_homescreen
    return await http_get(blink, url)
  File "/Users/dev/Library/Python/3.8/lib/python/site-packages/blinkpy/api.py", line 473, in http_get   
    return await blink.auth.query(
  File "/Users/dev/Library/Python/3.8/lib/python/site-packages/blinkpy/auth.py", line 174, in query
    return await self.validate_response(response, json_resp)
  File "/Users/dev/Library/Python/3.8/lib/python/site-packages/blinkpy/auth.py", line 137, in validate_response
    json_data = await response.json()
  File "/Users/dev/Library/Python/3.8/lib/python/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://rest-e007.immedia-semi.com/api/v3/accounts/[redacted]/homescreen')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10829aca0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1082c80a0>, 20.010839603)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x1082c88e0>, 20.622463577)]']
connector: <aiohttp.connector.TCPConnector object at 0x10829ad90>
```

**Expected behavior**
start () should either prompt to enter 2FA or return to my code without an exception

**`blinkpy` version (not needed if filling out Home Assistant version):**
0.23.0

**Additional Information**
Appears to be an error parsing http response from blink server.  Perhaps they changed the response format recently?

**Comment by ed2050** [comment]
I traced the problem a bit more.  The blink server returns `406 Not Acceptable` on the connection to https://rest-e007.immedia-semi.com/api/v3/accounts/[redacted]/homescreen.

It seems this problem has happened before.  See these related threads :
- https://github.com/home-assistant/core/issues/107143
- https://github.com/fronzbot/blinkpy/issues/818
- https://github.com/fronzbot/blinkpy/pull/848

Any ideas what to do?  One thread mentioned the old synchronous version still worked.  Should I downgrade?

**Comment by ed2050** [comment]
I finally fixed this.

I originally installed blinkpy in July with `pip install blinkpy`.  For some reason it installed 0.22.4 instead of 0.23.x.  0.22.4 was released in Dec 2023 before the user agent bug was fixed in Jan 2024.  There were several more 0.22 point releases after that.  No idea why I ended up with such an old version.

Fix was to update blinkpy/helpers/constants.py with the following:
```
DEFAULT_USER_AGENT = (
    "Mozilla/5.0 (Linux; Android 14) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.6099.193 Mobile Safari/537.36"
)
 ```

More info at https://github.com/home-assistant/core/issues/107143#issuecomment-1880033298.
